#[derive(Debug,Clone,Copy,PartialEq,Eq)]
pub struct ErrorInfo {
    pub code: &'static str,
    pub title: &'static str,
    pub fix: &'static str,
    pub retry: &'static str,
}

pub const ERRORS: &[ErrorInfo] = &[
    ErrorInfo { code:"MAIL1001", title:"Invalid email address", fix:"Use a trimmed address such as user@example.com and remove header/control characters.", retry:"never" },
    ErrorInfo { code:"MAIL1002", title:"Invalid message", fix:"Correct the concrete message field named by the diagnostic before retrying.", retry:"never" },
    ErrorInfo { code:"MAIL1003", title:"Invalid mail domain", fix:"Use a fully-qualified public DNS name without schemes, paths, spaces or invalid labels.", retry:"never" },
    ErrorInfo { code:"MAIL1004", title:"Invalid transport configuration", fix:"Validate transport credentials, sender identity, region/domain and provider-specific settings.", retry:"never" },
    ErrorInfo { code:"MAIL1005", title:"Invalid provider API path", fix:"Use a provider-local absolute path beginning with one slash; do not pass a full URL.", retry:"never" },
    ErrorInfo { code:"MAIL1006", title:"Unsupported provider HTTP method", fix:"Use a method supported by the provider endpoint and RBE net:http broker.", retry:"never" },
    ErrorInfo { code:"MAIL1007", title:"Provider credential missing", fix:"Supply the provider credential through authorized configuration; never hard-code it in source.", retry:"never" },
    ErrorInfo { code:"MAIL1008", title:"Invalid provider resource identifier", fix:"Correct the provider resource identifier named by the diagnostic.", retry:"never" },
    ErrorInfo { code:"MAIL1009", title:"Invalid Mailgun domain", fix:"Pass the verified Mailgun sending domain only, not a URL or path.", retry:"never" },
    ErrorInfo { code:"MAIL1010", title:"Invalid SendPulse domain", fix:"Pass only the domain registered and verified in SendPulse.", retry:"never" },
    ErrorInfo { code:"MAIL1011", title:"Invalid AWS region", fix:"Use a valid AWS region and ensure the SES identity exists in that region.", retry:"never" },
    ErrorInfo { code:"MAIL1012", title:"Invalid SendGrid legacy template id", fix:"Use a valid legacy template identifier only when that upstream compatibility path is supported.", retry:"never" },
    ErrorInfo { code:"MAIL1013", title:"Invalid SMTP endpoint", fix:"Use the documented SMTP address/port and keep secure STARTTLS/TLS enabled.", retry:"never" },
    ErrorInfo { code:"MAIL1014", title:"SMTP credential missing", fix:"Use the provider SMTP username/password/token pair; it may differ from API credentials.", retry:"never" },
    ErrorInfo { code:"MAIL1015", title:"Invalid DNS domain", fix:"Pass a fully-qualified public domain such as gmail.com.", retry:"never" },
    ErrorInfo { code:"MAIL1016", title:"Header injection rejected", fix:"Keep untrusted text out of structured headers and remove CR/LF injection attempts.", retry:"never" },
    ErrorInfo { code:"MAIL1017", title:"Invalid template variable", fix:"Use simple template variable names containing only supported characters.", retry:"never" },
    ErrorInfo { code:"MAIL1018", title:"Incomplete self-hosted setup", fix:"Provide valid domain/mail-host names, a publicly routable IP, and secure ownership token.", retry:"never" },
    ErrorInfo { code:"MAIL1019", title:"Invalid ownership verification token", fix:"Generate 32 CSPRNG bytes and pass their 64-character hexadecimal encoding.", retry:"never" },
    ErrorInfo { code:"MAIL1020", title:"Invalid self-hosted public IPv4 address", fix:"Use the publicly routable IPv4 address that actually receives SMTP for the mail host.", retry:"never" },
    ErrorInfo { code:"MAIL1021", title:"Invalid Message-ID or References chain", fix:"Use RFC-style Message-IDs and whitespace-separated valid References IDs.", retry:"never" },
    ErrorInfo { code:"MAIL1022", title:"Invalid unsubscribe target", fix:"RFC 8058 one-click requires HTTPS; non-one-click may use HTTPS or mailto where supported.", retry:"never" },
    ErrorInfo { code:"MAIL1023", title:"Invalid OTP content", fix:"Keep OTP product/code bounded and expiry within 1..=1440 minutes.", retry:"never" },
    ErrorInfo { code:"MAIL2001", title:"Required RBE capability missing", fix:"Approve the capability requested by mail and reactivate the package host session.", retry:"never" },
    ErrorInfo { code:"MAIL2002", title:"Self-hosted server prerequisite missing", fix:"Inspect self_hosted_capabilities() and approve every missing prerequisite before enabling server mode.", retry:"never" },
    ErrorInfo { code:"MAIL2003", title:"TCP capability missing", fix:"Approve net:tcp for mail and reactivate the package session; never bypass RBE with raw sockets.", retry:"never" },
    ErrorInfo { code:"MAIL2004", title:"TLS capability missing", fix:"Approve both net:tcp and net:tls for mail; never downgrade SMTP to plaintext.", retry:"never" },
    ErrorInfo { code:"MAIL2005", title:"DNS capability missing", fix:"Approve net:dns for mail and reactivate the package session.", retry:"never" },
    ErrorInfo { code:"MAIL2006", title:"RBE Library Host session unavailable", fix:"Run mail through activated RBE/RPX package hosting and inspect ABI/session diagnostics.", retry:"never" },
    ErrorInfo { code:"MAIL2007", title:"Secure verification-token generation unavailable", fix:"Approve crypto or supply a separately generated 256-bit ownership token.", retry:"never" },
    ErrorInfo { code:"MAIL4001", title:"Provider authentication rejected", fix:"Verify or rotate provider credentials and sender/domain permissions.", retry:"never" },
    ErrorInfo { code:"MAIL4002", title:"Provider rate limit exceeded", fix:"Honor provider Retry-After/backoff guidance and reduce concurrency.", retry:"backoff" },
    ErrorInfo { code:"MAIL4003", title:"Provider quota or billing limit reached", fix:"Fix provider billing/quota/account state before retrying.", retry:"never" },
    ErrorInfo { code:"MAIL4004", title:"Provider rejected the mail request", fix:"Inspect sanitized provider detail and correct the rejected field or policy.", retry:"conditional" },
    ErrorInfo { code:"MAIL4005", title:"Provider temporarily unavailable", fix:"Retry with exponential backoff or deliberately switch configured provider.", retry:"backoff" },
    ErrorInfo { code:"MAIL4006", title:"Provider request timed out", fix:"Treat delivery as ambiguous and query provider/idempotency state before resending.", retry:"ambiguous" },
    ErrorInfo { code:"MAIL4007", title:"RBE mail network operation failed", fix:"Inspect the underlying RBE broker diagnostic and retry only when the operation is safe.", retry:"conditional" },
    ErrorInfo { code:"MAIL4008", title:"RBE request or response limit exceeded", fix:"Reduce or split the message/request so it fits the active broker limits.", retry:"never" },
    ErrorInfo { code:"MAIL4009", title:"Recipient rejected", fix:"Correct the recipient or recipient policy before retrying.", retry:"conditional" },
    ErrorInfo { code:"MAIL4010", title:"SMTP TLS/STARTTLS unavailable", fix:"Approve net:tls/net:tcp and require STARTTLS; if the MX does not advertise STARTTLS, do not send plaintext.", retry:"never" },
    ErrorInfo { code:"MAIL4011", title:"Inbound SMTP listener unavailable", fix:"Approve net:tcp-listen for mail before starting the inbound SMTP listener.", retry:"never" },
    ErrorInfo { code:"MAIL4012", title:"Package mail.service unavailable", fix:"Approve service:package and ensure the verified package contains its service/**/*.service source.", retry:"never" },
    ErrorInfo { code:"MAIL4013", title:"DNS lookup failed", fix:"Inspect recipient DNS and the underlying RBE DNS diagnostic; back off on transient resolver failures.", retry:"backoff" },
    ErrorInfo { code:"MAIL4014", title:"No mail exchanger or address fallback", fix:"Correct the recipient domain; it has neither usable MX nor A/AAAA fallback.", retry:"never" },
    ErrorInfo { code:"MAIL4015", title:"Recipient domain publishes null MX", fix:"Do not retry this address: the domain explicitly declares that it accepts no email.", retry:"never" },
    ErrorInfo { code:"MAIL4016", title:"Temporary SMTP failure", fix:"Retry the affected recipient domain with exponential backoff; do not immediately hammer the same MX.", retry:"backoff" },
    ErrorInfo { code:"MAIL4017", title:"Permanent SMTP rejection", fix:"Inspect the SMTP stage/status and correct sender, recipient, message or remote policy before retrying.", retry:"never" },
    ErrorInfo { code:"MAIL4018", title:"Partial self-hosted delivery", fix:"Some recipient domains already accepted the message; retry only the undelivered recipients/domains to avoid duplicates.", retry:"ambiguous" },
    ErrorInfo { code:"MAIL4019", title:"SMTPUTF8 unsupported", fix:"Use ASCII envelope mailbox addresses until the self-hosted transport negotiates SMTPUTF8 explicitly.", retry:"never" },
    ErrorInfo { code:"MAIL5001", title:"Build prerequisite missing", fix:"Install or restore the named build prerequisite and rerun the build helper.", retry:"never" },
    ErrorInfo { code:"MAIL5002", title:"Latest green RBE commit could not be resolved", fix:"Check GitHub access/token or explicitly select a known-green full RBE SHA.", retry:"conditional" },
    ErrorInfo { code:"MAIL5003", title:"RBE source checkout or backend build failed", fix:"Fix the first Git/RBE compiler diagnostic; refresh .cache/rbe/upstream if corrupt.", retry:"conditional" },
    ErrorInfo { code:"MAIL5004", title:"RBE SDK bootstrap or status failed", fix:"Inspect backend install/sdk status and repair/reinstall the project-local .rbe SDK.", retry:"conditional" },
    ErrorInfo { code:"MAIL5005", title:"RPX validation or package compilation failed", fix:"Fix the first RPX/compiler diagnostic printed above MAIL5005 and rerun.", retry:"conditional" },
    ErrorInfo { code:"MAIL8001", title:"Malformed external or host response", fix:"Preserve sanitized response detail and RBE/package versions; report compatibility drift.", retry:"never" },
    ErrorInfo { code:"MAIL8002", title:"Malformed DNS response", fix:"Preserve the DNS response/RBE version and stop before SMTP; do not guess MX state.", retry:"never" },
    ErrorInfo { code:"MAIL8003", title:"Malformed SMTP or TLS broker response", fix:"Preserve sanitized SMTP/RBE response detail and stop the transaction; do not infer success from malformed protocol state.", retry:"never" },
    ErrorInfo { code:"MAIL9001", title:"Mail package invariant violated", fix:"Report the code, package version, RBE commit and a minimal reproducer.", retry:"never" },
    ErrorInfo { code:"MAIL9002", title:"Invalid system clock", fix:"Correct host time synchronization before constructing Date headers or signed provider requests.", retry:"never" },
];

pub fn explain(code: &str) -> Option<&'static ErrorInfo> {
    ERRORS.iter().find(|item| item.code.eq_ignore_ascii_case(code))
}
