#[derive(Debug,Clone,Copy,PartialEq,Eq)]
pub struct ErrorInfo {
    pub code: &'static str,
    pub title: &'static str,
    pub fix: &'static str,
    pub retry: &'static str,
}

pub const ERRORS: &[ErrorInfo] = &[
    ErrorInfo { code: "MAIL1001", title: "Invalid email address", fix: "Use a trimmed ASCII dot-atom address such as user@example.com.; Remove display/header control characters. Use Address::named() only with a normal display name.", retry: "never" },
    ErrorInfo { code: "MAIL1002", title: "Invalid message", fix: "Read the concrete error message and correct that message field before sending.; Do not retry unchanged invalid input.", retry: "never" },
    ErrorInfo { code: "MAIL1003", title: "Invalid mail domain", fix: "Use a fully-qualified domain such as example.com or mail.example.com.; Remove schemes, paths, underscores, spaces, and leading/trailing hyphens from DNS labels.", retry: "never" },
    ErrorInfo { code: "MAIL1004", title: "Invalid transport configuration", fix: "Validate the selected provider transport, sender identity, region/domain and credentials.; Use provider API credentials for API transports and provider SMTP credentials for SMTP transports.", retry: "never" },
    ErrorInfo { code: "MAIL1005", title: "Invalid provider API path", fix: "Pass an absolute provider-local path beginning with one /, for example /emails.; Do not pass full URLs to provider-native request_json().", retry: "never" },
    ErrorInfo { code: "MAIL1006", title: "Unsupported provider HTTP method", fix: "Use a method supported by both the provider endpoint and the RBE net:http broker.", retry: "never" },
    ErrorInfo { code: "MAIL1007", title: "Provider credential missing", fix: "Supply the provider credential through authorized RBE configuration; never hard-code it in source.; For SMTP, use SMTP credentials when the provider distinguishes them from API keys.", retry: "never" },
    ErrorInfo { code: "MAIL1008", title: "Invalid provider resource identifier", fix: "No recovery guidance until emitted.", retry: "never" },
    ErrorInfo { code: "MAIL1009", title: "Invalid Mailgun domain", fix: "Pass the verified Mailgun sending domain only, not a URL/path.", retry: "never" },
    ErrorInfo { code: "MAIL1010", title: "Invalid SendPulse domain", fix: "Pass only the domain registered/verified in SendPulse.", retry: "never" },
    ErrorInfo { code: "MAIL1011", title: "Invalid AWS region", fix: "Use an AWS region identifier such as ap-south-1 and ensure the SES identity exists in that region.", retry: "never" },
    ErrorInfo { code: "MAIL1012", title: "Invalid SendGrid legacy template id", fix: "Use a valid legacy template id only when the upstream SendGrid legacy-template feature is still appropriate.", retry: "never" },
    ErrorInfo { code: "MAIL1013", title: "Invalid SMTP endpoint", fix: "Use the provider-documented SMTP hostname and port.; Prefer STARTTLS/TLS profiles and never downgrade to plaintext to bypass MAIL2004/MAIL4010.", retry: "never" },
    ErrorInfo { code: "MAIL1014", title: "SMTP credential missing", fix: "Open the provider SMTP settings and use its documented SMTP username/password/token pair.", retry: "never" },
    ErrorInfo { code: "MAIL1015", title: "Invalid DNS domain", fix: "Pass a fully-qualified public domain such as gmail.com.", retry: "never" },
    ErrorInfo { code: "MAIL1016", title: "Header injection rejected", fix: "Keep untrusted/user text in the body. Validate/encode structured header values before passing them to mail.", retry: "never" },
    ErrorInfo { code: "MAIL1017", title: "Invalid template variable", fix: "Use simple variable names such as first_name or order-id.", retry: "never" },
    ErrorInfo { code: "MAIL1018", title: "Incomplete self-hosted setup", fix: "Use setup_records_with_token() with valid example.com / mail.example.com names, a public IPv4 address, and a secure verification token.", retry: "never" },
    ErrorInfo { code: "MAIL1019", title: "Invalid ownership verification token", fix: "Generate 32 cryptographically random bytes outside the package and pass their 64-character hex encoding to setup_records_with_token().; Do not derive ownership tokens from timestamps, domains, counters or user ids.", retry: "never" },
    ErrorInfo { code: "MAIL1020", title: "Invalid self-hosted public IPv4 address", fix: "Use the publicly routable IPv4 address that will actually receive SMTP for mail.<domain>.; If you need IPv6-only setup, use a future AAAA/ip6-aware setup surface rather than lying in an A/ip4 record.", retry: "never" },
    ErrorInfo { code: "MAIL1021", title: "Invalid Message-ID or References chain", fix: "Use RFC-style Message-IDs such as <opaque-id@example.com>.; Pass References as whitespace-separated Message-IDs only.", retry: "never" },
    ErrorInfo { code: "MAIL1022", title: "Invalid unsubscribe target", fix: "For RFC 8058 one-click, use an HTTPS unsubscribe URI.; For non-one-click List-Unsubscribe, https:// or mailto: is accepted by this helper.", retry: "never" },
    ErrorInfo { code: "MAIL1023", title: "Invalid OTP content", fix: "Keep product/code at 128 characters or fewer and expiry between 1 and 1440 minutes.; HTML is escaped automatically; do not pre-inject markup into product/code.", retry: "never" },
    ErrorInfo { code: "MAIL2001", title: "Required RBE capability missing", fix: "Inspect the package approval/grant state and approve the required capability when RBE supports it.; Reactivate/restart the package session after grants change.", retry: "never" },
    ErrorInfo { code: "MAIL2002", title: "Self-hosted server prerequisite missing", fix: "Call self_hosted_capabilities() and enable every missing prerequisite.; Use a provider transport until current RBE supplies the missing package-host primitives.", retry: "never" },
    ErrorInfo { code: "MAIL2003", title: "TCP capability missing", fix: "Do not bypass RBE with std::net/raw sockets. Use provider HTTP mode until RBE net:tcp is implemented and granted.", retry: "never" },
    ErrorInfo { code: "MAIL2004", title: "TLS capability missing", fix: "Never downgrade to plaintext SMTP. Use provider HTTPS mode or wait for RBE TLS authority.", retry: "never" },
    ErrorInfo { code: "MAIL2005", title: "DNS capability missing", fix: "Approve net:dns for mail and reactivate the package session.", retry: "never" },
    ErrorInfo { code: "MAIL2006", title: "RBE Library Host session unavailable", fix: "Execute the component through RBE/RPX package activation, not as a standalone binary.; Check SDK ABI/session logs if the package should already be hosted.", retry: "never" },
    ErrorInfo { code: "MAIL2007", title: "Secure verification-token generation unavailable", fix: "Generate 32 random bytes with a trusted CSPRNG outside the package and call setup_records_with_token() with 64 hex characters.; Do not fall back to timestamp-derived tokens.", retry: "never" },
    ErrorInfo { code: "MAIL4001", title: "Provider authentication rejected", fix: "Verify/rotate the provider credential and sender/domain permissions.; Do not retry unchanged credentials.", retry: "never" },
    ErrorInfo { code: "MAIL4002", title: "Provider rate limit exceeded", fix: "Honor Retry-After/provider backoff semantics and reduce request concurrency.", retry: "backoff" },
    ErrorInfo { code: "MAIL4003", title: "Provider quota or billing limit reached", fix: "Fix provider billing/quota/account state before retrying.", retry: "never" },
    ErrorInfo { code: "MAIL4004", title: "Provider rejected the mail request", fix: "Inspect provider-detail and correct the rejected field/policy before retrying.", retry: "conditional" },
    ErrorInfo { code: "MAIL4005", title: "Provider temporarily unavailable", fix: "Retry with exponential backoff, or deliberately switch provider if your application supports that policy.", retry: "backoff" },
    ErrorInfo { code: "MAIL4006", title: "Provider request timed out", fix: "Treat delivery as ambiguous: query provider/idempotency state before resending.; Use an idempotency key where the provider supports it.", retry: "ambiguous" },
    ErrorInfo { code: "MAIL4007", title: "RBE mail network operation failed", fix: "Inspect the underlying RBE broker diagnostic (HTTP3000/DNS3000/etc.).; Retry only if the failed operation is known to be safe/idempotent.", retry: "conditional" },
    ErrorInfo { code: "MAIL4008", title: "RBE request or response limit exceeded", fix: "Reduce/split message, attachment or provider request data so it fits the active RBE broker limits.; Do not blindly retry the same oversized payload.", retry: "never" },
    ErrorInfo { code: "MAIL4009", title: "Recipient rejected", fix: "No recovery guidance until emitted.", retry: "conditional" },
    ErrorInfo { code: "MAIL4010", title: "SMTP TLS/STARTTLS unavailable", fix: "Do not send plaintext. Use provider HTTPS mode until RBE TLS/STARTTLS is implemented/granted.", retry: "never" },
    ErrorInfo { code: "MAIL4011", title: "Inbound SMTP listener unavailable", fix: "Enable the RBE package listener primitive when implemented; keep server mode disabled meanwhile.", retry: "never" },
    ErrorInfo { code: "MAIL4012", title: "Package mail.service unavailable", fix: "Use provider-only mode until RBE can register/activate package-owned mail.service.", retry: "never" },
    ErrorInfo { code: "MAIL4013", title: "DNS lookup failed", fix: "Check the recipient/domain DNS externally and inspect the underlying DNS3000 detail.; Retry transient DNS failures with backoff.", retry: "backoff" },
    ErrorInfo { code: "MAIL4014", title: "No mail exchanger or address fallback", fix: "Correct the recipient domain/address. This is not fixed by retrying the same invalid domain.", retry: "never" },
    ErrorInfo { code: "MAIL4015", title: "Recipient domain publishes null MX", fix: "Do not retry. Correct the recipient/domain or use another contact address.", retry: "never" },
    ErrorInfo { code: "MAIL5001", title: "Build prerequisite missing", fix: "Install/restore the prerequisite named in the error and rerun build.ps1/build.sh.", retry: "never" },
    ErrorInfo { code: "MAIL5002", title: "Latest green RBE commit could not be resolved", fix: "Check GitHub access or set GITHUB_TOKEN.; Pass -RbeSha/--rbe-sha with a known-green full SHA as an explicit fallback.", retry: "conditional" },
    ErrorInfo { code: "MAIL5003", title: "RBE source checkout or backend build failed", fix: "Read the underlying Git/RBE compiler output.; Delete .cache/rbe/upstream to refresh a corrupt checkout and retry.", retry: "conditional" },
    ErrorInfo { code: "MAIL5004", title: "RBE SDK bootstrap or status failed", fix: "Inspect backend install/sdk status output and repair/reinstall .rbe.; If CLI syntax changed upstream, compare against backend install help.", retry: "conditional" },
    ErrorInfo { code: "MAIL5005", title: "RPX validation or package compilation failed", fix: "Fix the first compiler/RPX/RBE diagnostic printed above MAIL5005 and rerun.; Use host-toolchain escape hatch only for deliberate local development when no managed toolchain exists.", retry: "conditional" },
    ErrorInfo { code: "MAIL8001", title: "Malformed external or host response", fix: "Preserve the sanitized raw detail, package version and RBE commit; report compatibility drift.; Do not guess status/success when required metadata is malformed.", retry: "never" },
    ErrorInfo { code: "MAIL8002", title: "Malformed DNS response", fix: "Preserve the DNS response/RBE version and report the incompatibility.; Do not proceed to SMTP with malformed MX data.", retry: "never" },
    ErrorInfo { code: "MAIL9001", title: "Mail package invariant violated", fix: "Report the code, MailError::diagnostic(), package version and RBE commit with a minimal reproducer.", retry: "never" },
    ErrorInfo { code: "MAIL9002", title: "Invalid system clock", fix: "Correct the host clock/time synchronization and retry.; For SES, also ensure clock skew is within AWS signing tolerance.", retry: "never" },
];

pub fn explain(code: &str) -> Option<&'static ErrorInfo> {
    ERRORS.iter().find(|item| item.code.eq_ignore_ascii_case(code))
}
